### ISSUE TITLE
Please upgrade minimatch version

### ISSUE THREAD

**Issue by ainthek** [fnobi/ejs-cli#19]
$ snyk test ejs-cli
(node:8236) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

Testing ejs-cli...

✗ High severity vulnerability found in minimatch
  Description: Regular Expression Denial of Service (DoS)
  Info: https://snyk.io/vuln/npm:minimatch:20160620
  Introduced through: glob@3.2.11
  From: glob@3.2.11 > minimatch@0.3.0

Organization:      ainthek
Package manager:   npm
Open source:       yes
Project path:      ejs-cli

Tested ejs-cli for known vulnerabilities, found 1 vulnerability, 1 vulnerable path.

**Comment by fnobi** [comment]
@ainthek 
it has been fixed in this commit! https://github.com/fnobi/ejs-cli/commit/e23b1e38ceb6036a977148421f2d0c3b2d86732c#diff-32607347f8126e6534ebc7ebaec4853dR977
thanks for reporting.
