### ISSUE TITLE
`colors` dependency is missing

### ISSUE THREAD

**Issue by eungook** [fnobi/ejs-cli#32]
when file output mode, the `ejs-cli` write the log. but now 😢
```
undefined
```

because the `colors` dependency is [missing](https://github.com/fnobi/ejs-cli/pull/26) now. please help! 🥲
https://github.com/fnobi/ejs-cli/blob/a9b35262fd1ac3abef77761a967d24de07335461/lib/cli.js#L66

**Comment by fnobi** [comment]
@eungook 
Thanks for the report!

The problem here was solved by installing [chalk](https://www.npmjs.com/package/chalk).
It is now released as well, so please check it out.

* https://github.com/fnobi/ejs-cli/pull/34
* https://www.npmjs.com/package/ejs-cli/v/2.2.3

**Comment by eungook** [comment]
@fnobi it works great! thank you! 🙂🙂🙂🙂🙂🙂🙂
