### ISSUE TITLE
EJS Dependency

### ISSUE THREAD

**Issue by RyanZim** [fnobi/ejs-cli#8]
The package.json lists EJS v0.8.5 as a dependency.

Work at [tj/ejs](https://github.com/tj/ejs) has stalled, and EJS version 2 is now being actively developed at [mde/ejs](https://github.com/mde/ejs) (where I am a collaborator).

The API should be compatible, however, the EJS syntax has changed some. Most notably, the filters feature has been removed.

See the [CHANGELOG](https://github.com/mde/ejs/blob/master/CHANGELOG.md#v201-2015-01-02) for a complete list of changes.

Would you consider upgrading the dependency to EJS v2.4.1?

**Comment by nobii** [comment]
@RyanZim thanks!
The dependency version has been upgraded. 3710e6ba17c70ec390cd56d29bb627933c56a14f

**Comment by RyanZim** [comment]
@nobii thanks you!

However, wouldn't this be a breaking change (major version bump) according to http://semver.org/ since the EJS syntax has changed?

**Comment by RyanZim** [comment]
Perhaps we should resolve #9 before bumping the major just in case we break backwards compatibility there.

**Comment by RyanZim** [comment]
@nobii @fnobi ping?

**Comment by fnobi** [comment]
version 2.0.0 is released! 
https://www.npmjs.com/package/ejs-cli

and 1.2.0 has been [depredated](https://docs.npmjs.com/cli/deprecate).

**Comment by RyanZim** [comment]
Thanks!

SemVer seems to recommend publishing v1.3.0 as well to catch those that have their dependency specified as `^1.0.0`.

http://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version

**Comment by RyanZim** [comment]
@nobii @fnobi ping?

**Comment by RyanZim** [comment]
@nobii @fnobi ping?

**Comment by RyanZim** [comment]
Closing since I don't use ejs-cli much anymore.
